1.1
Tihon-k/examples pull request #1
Opened 2024-07-18 16:59 UTC by Tihon-k

2024-07-20 18:54 UTC, Tihon-k commented on src/Ex10/Ex10Main.java
> +            //Интересно, а как сделать нумерацию в array list?
Если можно как-то это сделать, можешь показать как?

2024-07-22 15:23 UTC, DMatveeva requested changes

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/SetSomething.java
> +public interface SetSomething {
для чего этот интерфейс? 
Интерфейсы обычно называются именем прилагательным

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Shape.java
> +    public double [] setBall(){
для чего эти методы setBall и т.д.?

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Box.java
> +    public void foo() {
в классе по названиям методов должно быть понятно, что этот метод делает. Foo - это непонятно

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Box.java
> +    public double add() {
метод add предполагает, что ты что-то добавляешь в коробку. Это "что-то" - это трехмерная фигура, которая передается в качестве параметра метода add.

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Pyramid.java
> +    private double side = 5;
эти параметры должны задаваться в конструкторе

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Pyramid.java
> +    public double getVolume(){
все переопределенные методы должны быть с аннотацией Override

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/GetVolume.java
> +public interface GetVolume {
это лишний интерфейс. getVolume и так объявлен в классе Shape

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Ball.java
> +        setRadius(1);
радиус должен задаваться в конструкторе

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Box.java
> +    Ball ball = new Ball();
этих всех фигур быть не должно

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Box.java
> +            System.out.println(list);
не надо выводить в консоль

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Box.java
> +        double n  = volume - (ball.volume + cylinder.volume + pyramid.volume);
здесь только volume - shape.getVolume

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Cylinder.java
> +    private double height = 1;
в конструкторе

2024-07-22 15:23 UTC, DMatveeva commented on src/Ex10/Shape.java
> +    double volume;
а getVolume?

2024-07-23 07:56 UTC, DMatveeva requested changes

2024-07-23 07:56 UTC, DMatveeva commented on src/Ex10/Ball.java
>          volume = 3/4*Math.PI* Math.pow(getRadius(),4);
можно просто return 3/4*Math....

2024-07-23 07:56 UTC, DMatveeva commented on src/Ex10/Box.java
>          List<Double> list = new ArrayList<>();
это тоже убрать

2024-07-23 07:56 UTC, DMatveeva commented on src/Ex10/Box.java
метод comparable не нужен

2024-07-23 07:56 UTC, DMatveeva commented on src/Ex10/Cylinder.java
>          volume = height * Math.PI * Math.pow(getRadius(),2);
просто return...

2024-07-23 07:56 UTC, DMatveeva commented on src/Ex10/SolidORevolution.java
>      protected double getRadius() {
почему protected? этот метод как раз должен быть доступен всем

2024-07-24 07:00 UTC, DMatveeva requested changes

2024-07-24 07:00 UTC, DMatveeva commented on src/Ex10/Ball.java
> +        return 3/4*Math.PI* Math.pow(getRadius(),4);
проверь  результат, скорее всего тут всегда 0

2024-07-24 07:00 UTC, DMatveeva commented on src/Ex10/Box.java
>          if (this.volume >= 0) {
просто return this.volume >= 0

2024-07-24 07:00 UTC, DMatveeva commented on src/Ex10/Pyramid.java
> +        return height * Math.pow(side,2) * Math.sqrt(3) / 4;
проверь результат, / - возвращает целую часть от деления

2024-07-25 08:12 UTC, DMatveeva requested changes

2024-07-25 08:12 UTC, DMatveeva commented on src/Ex11/Converter.java
> +    public double getConverter(double t);
лучше назвать метод convert, ты же конвертируешь, а не возвращает конвертер
и еще вопрос, что такое t? это по какой шкале температура? а , увидела, по Цельсию. Тогда надо написать celsiumTemp как-то так, чтобы было понятно

2024-07-29 16:05 UTC, DMatveeva requested changes

2024-07-29 16:05 UTC, DMatveeva commented on src/Ex12/Reciver.java
> +public class Reciver {
класс с stringBuilder в названии

2024-07-29 16:05 UTC, DMatveeva commented on src/Ex12/Reciver.java
> +    public void builder(StringBuilder sb, String str){
методы называться глаголам, append

2024-07-29 16:05 UTC, DMatveeva commented on src/Ex12/Reciver.java
> +    public void builder(StringBuilder sb, String str){
использовать sb

2024-07-29 16:05 UTC, DMatveeva commented on src/Ex12/Reciver.java
> +        this.sb = sb;
это не надо

2024-07-29 16:05 UTC, DMatveeva commented on src/Ex12/Reciver.java
> +        int i = historyList.lastIndexOf(str);
это не надо

2024-07-29 16:05 UTC, DMatveeva commented on src/Ex12/Reciver.java
> +    List historyList = new ArrayList();
List String

2024-07-29 16:05 UTC, DMatveeva commented on src/Ex12/Reciver.java
> +    public void deleteLast() {
undo

2024-07-29 16:05 UTC, DMatveeva commented on src/Ex12/Reciver.java
> +        historyList.remove(i);
removeLast

2024-07-29 17:07 UTC, DMatveeva approved these changes

2024-07-29 17:17 UTC, merged